# Exercise 8.1


#### 8.1.2) Write a Python routine first that for any matrix A returns the first  4 singular vector. You may usenumpy.linalg.svd() for this

In [97]:
import numpy as np
import pprint as pp

In [98]:
def first(A: np.array):
    u, sv, v = np.linalg.svd(A, full_matrices=False) # u, sv, v = left singular vector, singular values, right singular vector
    # print(u,sv,v)
    return v[0] #return the first singular vector
     

#### 8.1.3) randomly generate a matrix for at least dimension d= 4and sample  3 size n= 8(to get an n×d-matrix). Apply this routine to the matrix to obtain the first singular vector and apply (i) to also obtain the second


In [99]:
n = 8
d = 4
A = np.random.sample((8,4)) # generate a matrix randomly
print('Generated matrix A: ')
pp.pprint(A)
v1_A = np.reshape(first(A), (-1,1)) # get the first singular vector of matrix A
#print(np.identity(d))
#print(np.matmul(v1, v1.T))

A_prime = np.matmul(A, np.identity(d) - np.matmul(v1_A,v1_A.T)) 
v1_A_prime = np.reshape(first(A_prime),(-1,1)) # get the first singular vector of matrix A prime
v1_A_prime = v1_A_prime.round(7) # round the vector 

Generated matrix A: 
array([[0.91328558, 0.32004273, 0.94728329, 0.78185104],
       [0.21562772, 0.69043145, 0.30977533, 0.0478615 ],
       [0.91327326, 0.64679348, 0.11148267, 0.63425372],
       [0.05799109, 0.92588446, 0.9632166 , 0.26026111],
       [0.36775821, 0.87204026, 0.46425881, 0.69485968],
       [0.27088429, 0.20241193, 0.88388272, 0.37510184],
       [0.1218639 , 0.83030021, 0.86817164, 0.10860723],
       [0.1286593 , 0.46462597, 0.56858142, 0.61408942]])


#### 8.1.4) compare numerically the second singular vector to the vector|v1〉1from the SVD given by numpy

In [100]:
u, sv, v = np.linalg.svd(A, full_matrices=False) # u, sv, v = left singular vector, singular values, right singular vector
v2_A = np.reshape( v[1] ,(-1,1))
v2_A = v2_A.round(7)

print('\n first singular vector of A prime:')
pp.pprint(v1_A_prime)
print('\n second singular vector of A :')
pp.pprint(v2_A)

if (v1_A_prime == v2_A).all() or (v1_A_prime == -1*v2_A).all(): # when both vectors are heading to the same direction or to exact opposite direction 
    print('\nv1_A_prime and v2_A are the same')
else:
    print('\nv1_A_prime and v2_A are not the same')



 first singular vector of A prime:
array([[-0.7019363],
       [ 0.3422305],
       [ 0.4221672],
       [-0.4603678]])

 second singular vector of A :
array([[-0.7019363],
       [ 0.3422305],
       [ 0.4221672],
       [-0.4603678]])

v1_A_prime and v2_A are the same


#### 8.1.5) With a method similar to (i), compute also the third singular vector and compare it to the SVD


In [101]:
v3_A = np.reshape(v[2],(-1,1)) # second singular vector of matrix A

A_two_prime = np.matmul(A, np.identity(d) - np.matmul(v1_A, v1_A.T) - np.matmul(v2_A, v2_A.T)) # compute the matrix A two prime
v1_A_two_prime = np.reshape(first(A_two_prime), (-1,1)) # compute the first singular vector of the matrix A two prime


print('\n first singular vector of A two prime:')
pp.pprint(v1_A_two_prime)
print('\n third singular vector of A :')
pp.pprint(v3_A)

if (v1_A_two_prime == v3_A).all() or (v1_A_two_prime == -1*v3_A).all(): # when both vectors are heading to the same direction or to exact opposite direction 
    print('\nv1_A_two_prime and v3_A are the same')
else:
    print('\nv1_A_two_prime and v3_A are not the same')






 first singular vector of A two prime:
array([[ 0.02616162],
       [ 0.74994548],
       [-0.65566733],
       [-0.08365227]])

 third singular vector of A :
array([[ 0.02616163],
       [ 0.74994548],
       [-0.65566733],
       [-0.08365226]])

v1_A_two_prime and v3_A are not the same
