In [28]:
'''
 * User: Hojun Lim
 * Date: 2020-06-18
'''

import numpy as np
import pprint as pp
import scipy

In [18]:
A = np.array([[1,0,1,0,0],
              [1,1,0,0,0],
              [0,1,0,0,0],
              [0,1,1,0,0],
              [0,0,0,1,0],
              [0,0,1,1,0],
              [0,0,0,1,0],
              [0,0,0,1,1]])


u, sv, v = np.linalg.svd(A, full_matrices=False) # u, sv, v = left singular vector, singular values, right singular vector

u1 = np.reshape(u[:,0],(-1,1))
sv1 = sv[0]
v1 = np.reshape(v[0,:], (1,-1))

u2 = np.reshape(u[:,1],(-1,1))
sv2 = sv[1]
v2 = np.reshape(v[1,:], (1,-1))

#Exercise 9.1.1
A2 = sv1*np.matmul(u1,v1) + sv2*np.matmul(u2,v2) # A2 = 2 truncated A
np.set_printoptions(suppress=True)
pp.pprint(np.round(A2, decimals=3))


array([[ 0.486,  0.673,  0.651,  0.154,  0.001],
       [ 0.551,  0.781,  0.608, -0.195, -0.104],
       [ 0.323,  0.458,  0.35 , -0.13 , -0.065],
       [ 0.58 ,  0.809,  0.744,  0.089, -0.026],
       [-0.065, -0.13 ,  0.219,  0.847,  0.245],
       [ 0.192,  0.22 ,  0.613,  1.067,  0.284],
       [-0.065, -0.13 ,  0.219,  0.847,  0.245],
       [-0.104, -0.196,  0.259,  1.092,  0.318]])


In [24]:
#Exercise 9.1.2

y = np.reshape(np.array([0,0,0,0.5,0,0.5,0,0]),(-1,1))
print('A^{T} y = :')
pp.pprint(np.matmul(A.T, y))
print()
print('A2^{T} y = :')
pp.pprint(np.matmul(A2.T, y))

A^{T} y = :
array([[0. ],
       [0.5],
       [1. ],
       [0.5],
       [0. ]])

A2^{T} y = :
array([[0.38638611],
       [0.51428595],
       [0.67825179],
       [0.57779359],
       [0.12898205]])


In [27]:
#Exercise 9.1.3
print('The Error: norm(A-A2) = ', np.linalg.norm(A-A2))
print('The upper bound of Error (A- AK) is k-th singlular value, and the Error when K = 2 is ', sv1)

The Error: norm(A-A2) =  1.9329446892818882
The upper bound of Error (A- AK) is k-th singlular value, and the Error when K = 2 is  2.2852979298701865


In [34]:
# Exercise 9.1.4
B = np.array([[0,0,0,0,0],
              [0,1,0,0,0],
              [0,1,0,0,0],
              [0,1,0,0,0],
              [0,0,0,1,0],
              [0,0,0,1,0],
              [0,0,0,1,0],
              [0,0,0,1,0]])

A_sub_B = A-B
F_norm_A_sub_B = np.sqrt(np.sum(np.square(A_sub_B)))
L2_norm_A_sub_B =np.linalg.norm(A_sub_B, ord=2) #2-norm of a matrix
print('F-norm of A-B = ')
pp.pprint(F_norm_A_sub_B)
print('L2-norm of A-B = ')
pp.pprint(L2_norm_A_sub_B)

A_sub_A2 = A-A2
F_norm_A_sub_A2 = np.sqrt(np.sum(np.square(A_sub_A2)))
L2_norm_A_sub_A2 = np.linalg.norm(A_sub_A2, ord=2) #2-norm of a matrix
print('F-norm of A-A2 = ')
pp.pprint(F_norm_A_sub_A2)
print('L2-norm of A-A2 = ')
pp.pprint(L2_norm_A_sub_A2)

F-norm of A-B = 
2.449489742783178
L2-norm of A-B = 
1.902113032590307
F-norm of A-A2 = 
1.9329446892818882
L2-norm of A-A2 = 
1.3606993083324652
